version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/stationerydb
    depends_on:
      - mongo
    volumes:
      - ./public:/app/public
      - ./src/views:/app/src/views
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=stationerydb
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: 